import {
  useEffect,
  useMemo,
  useState } from 'react';
import { ScrollView,
  StyleSheet,
  Text,
  View
} from 'react-native';
import TouchableOpacity from '../ui/SmoothTouchable';

import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { Ionicons } from '@expo/vector-icons';
import { fetchOSRMDistance, formatTag, groupFitLabel, primaryExplanation } from '../../constants/interactive';
import { COLORS, FONTS, RADIUS, TYPE } from '../../constants/theme';

function money(value) {
  const n = Number(value || 0);
  if (!Number.isFinite(n) || n <= 0) return null;
  return `EUR ${n.toFixed(n % 1 === 0 ? 0 : 1)}`;
}

export default function TripSummary({
  tripItems,
  days,
  country,
  saving = false,
  isAutoGenerated = false,
  onBack,
  onEdit,
  onSave,
  onDelete,
  onMove,
  onReplace,
  onMemory,
  onRegenerate,
  regenerating = false,
}) {
  const insets = useSafeAreaInsets();
  const [activeDay, setActiveDay] = useState(1);
  const [legs, setLegs] = useState({});
  const [allDayKms, setAllDayKms] = useState({});

  const dayItems = tripItems.filter((item) => item.day === activeDay);
  const cityName = dayItems[0]?.city?.city ?? dayItems[0]?.city?.name ?? '-';

  const totalCost = useMemo(
    () => tripItems.reduce((sum, item) => sum + Number(item.attraction?.entry_fee_eur || 0), 0),
    [tripItems]
  );
  const totalHours = useMemo(
    () => tripItems.reduce((sum, item) => sum + Number(item.attraction?.avg_duration_hours || 1), 0),
    [tripItems]
  );

  useEffect(() => {
    let cancelled = false;
    setLegs({});
    dayItems.forEach((item, index) => {
      if (index >= dayItems.length - 1) return;
      const next = dayItems[index + 1];
      if (!item.attraction?.lat || !next.attraction?.lat) return;
      fetchOSRMDistance(item.attraction, next.attraction)
        .then((legText) => {
          if (!cancelled) setLegs((prev) => ({ ...prev, [index]: legText }));
        })
        .catch(() => {
          if (!cancelled) setLegs((prev) => ({ ...prev, [index]: null }));
        });
    });
    return () => {
      cancelled = true;
    };
  }, [activeDay, tripItems]);

  useEffect(() => {
    let cancelled = false;
    for (let day = 1; day <= days; day += 1) {
      const items = tripItems.filter((item) => item.day === day);
      if (items.length < 2) {
        setAllDayKms((prev) => ({ ...prev, [day]: 0 }));
        continue;
      }
      const promises = [];
      for (let index = 0; index < items.length - 1; index += 1) {
        const from = items[index].attraction;
        const to = items[index + 1].attraction;
        if (from?.lat && to?.lat) {
          promises.push(
            fetchOSRMDistance(from, to)
              .then((text) => {
                const km = parseFloat((text || '').split(' km')[0]);
                return Number.isFinite(km) ? km : 0;
              })
              .catch(() => 0)
          );
        }
      }
      Promise.all(promises).then((kms) => {
        if (!cancelled) {
          const total = kms.reduce((a, b) => a + b, 0);
          setAllDayKms((prev) => ({ ...prev, [day]: total }));
        }
      });
    }
    return () => {
      cancelled = true;
    };
  }, [tripItems, days]);

  const dayKm = Object.values(legs)
    .reduce((sum, leg) => {
      const km = parseFloat((leg || '').split(' km')[0]);
      return Number.isFinite(km) ? sum + km : sum;
    }, 0)
    .toFixed(1);

  const totalKmAllDays = Object.values(allDayKms)
    .reduce((a, b) => a + b, 0)
    .toFixed(1);

  const costLabel = totalCost > 0 ? `~${money(totalCost)} entry fees` : 'No known entry fees';

  return (
    <View style={[styles.container, { paddingTop: insets.top }]}>
      <View style={styles.header}>
        <View style={styles.headerRow}>
          {onBack ? (
            <TouchableOpacity onPress={onBack} activeOpacity={0.8} style={styles.backBtn}>
              <Text style={styles.backBtnText}>{'<'}</Text>
            </TouchableOpacity>
          ) : null}
          <View style={styles.iconBox}>
            <Ionicons name="compass-outline" size={18} color={COLORS.primary} />
          </View>
          <Text style={styles.brandText}>TripCraft</Text>
          <View style={styles.tripLabelRow}>
            <Text style={styles.tripLabel}>Your Trip - {country || 'Europe'}</Text>
            {isAutoGenerated ? (
              <View style={styles.autoBadge}>
                <Text style={styles.autoBadgeText}>Auto-generated</Text>
              </View>
            ) : null}
          </View>
        </View>

        <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.tabsRow}>
          {Array.from({ length: days }, (_, index) => index + 1).map((day) => (
            <TouchableOpacity
              key={day}
              style={[styles.tab, activeDay === day && styles.tabActive]}
              activeOpacity={0.8}
              onPress={() => setActiveDay(day)}
            >
              <Text style={[styles.tabText, activeDay === day && styles.tabTextActive]}>Day {day}</Text>
            </TouchableOpacity>
          ))}
        </ScrollView>
      </View>

      <ScrollView style={styles.scroll} contentContainerStyle={styles.scrollContent} showsVerticalScrollIndicator={false}>
        <View style={styles.dayHeader}>
          <Text style={styles.dayTitle}>Day {activeDay} - {cityName}</Text>
          {dayKm !== '0.0' ? <Text style={styles.routeKm}>~{dayKm} km route</Text> : null}
        </View>

        {dayItems.length === 0 ? (
          <View style={styles.emptyState}>
            <Text style={styles.emptyText}>No attractions added for Day {activeDay} yet.</Text>
          </View>
        ) : (
          dayItems.map((item, index) => (
            <TimelineItem
              key={item.uid || `${activeDay}-${item.attraction.id}-${index}`}
              item={item}
              index={index}
              dayItems={dayItems}
              leg={legs[index]}
              onMove={onMove}
              onDelete={onDelete}
              onReplace={onReplace}
              onMemory={onMemory}
            />
          ))
        )}
      </ScrollView>

      <View style={[styles.footer, { paddingBottom: insets.bottom + 12 }]}>
        <View style={styles.statsBar}>
          <Text style={styles.statsText}>
            {days} day{days !== 1 ? 's' : ''} - {tripItems.length} stop{tripItems.length !== 1 ? 's' : ''} - ~{totalKmAllDays} km - ~{totalHours.toFixed(1)}h - {costLabel}
          </Text>
        </View>

        <View style={styles.footerBtns}>
          {onRegenerate ? (
            <TouchableOpacity
              style={[styles.regenerateBtn, regenerating && styles.saveBtnDisabled]}
              activeOpacity={0.8}
              onPress={onRegenerate}
              disabled={regenerating}
            >
              <Ionicons name="sparkles-outline" size={16} color={COLORS.primary} />
              <Text style={styles.regenerateBtnText}>{regenerating ? 'Refreshing...' : 'Regenerate'}</Text>
            </TouchableOpacity>
          ) : null}
          {onEdit ? (
            <TouchableOpacity style={styles.editBtn} activeOpacity={0.8} onPress={onEdit}>
              <Text style={styles.editBtnText}>Edit</Text>
            </TouchableOpacity>
          ) : null}
          {onSave ? (
            <TouchableOpacity
              style={[styles.saveBtn, saving && styles.saveBtnDisabled]}
              activeOpacity={0.85}
              onPress={onSave}
              disabled={saving}
            >
              <Text style={styles.saveBtnText}>{saving ? 'Saving...' : 'Save Trip'}</Text>
            </TouchableOpacity>
          ) : null}
          {!onEdit && !onSave && onBack ? (
            <TouchableOpacity style={styles.saveBtn} activeOpacity={0.85} onPress={onBack}>
              <Text style={styles.saveBtnText}>Back</Text>
            </TouchableOpacity>
          ) : null}
        </View>
      </View>
    </View>
  );
}

function TimelineItem({ item, index, dayItems, leg, onMove, onDelete, onReplace, onMemory }) {
  const reason = primaryExplanation(item.attraction);
  const fit = groupFitLabel(item.attraction);
  const fee = money(item.attraction.entry_fee_eur);

  return (
    <View style={styles.timelineRow}>
      <View style={styles.timelineLeft}>
        <View style={styles.dot} />
        {index < dayItems.length - 1 ? <View style={styles.line} /> : null}
      </View>

      <View style={styles.timelineContent}>
        <View style={styles.nameRow}>
          <Text style={[styles.itemName, { flex: 1 }]}>{item.attraction.name}</Text>
          {(onMove || onDelete || onReplace || onMemory) ? (
            <View style={styles.itemActions}>
              {onMemory ? (
                <>
                  <TouchableOpacity onPress={() => onMemory(item, 'like')} hitSlop={8}>
                    <View style={styles.memoryLikeBtn}>
                      <Ionicons name="heart-outline" size={14} color={COLORS.primary} />
                    </View>
                  </TouchableOpacity>
                  <TouchableOpacity onPress={() => onMemory(item, 'dislike')} hitSlop={8}>
                    <View style={styles.memoryDislikeBtn}>
                      <Ionicons name="remove-circle-outline" size={14} color={COLORS.error} />
                    </View>
                  </TouchableOpacity>
                </>
              ) : null}
              {onReplace ? (
                <TouchableOpacity onPress={() => onReplace(item)} hitSlop={8}>
                  <View style={styles.replaceBtn}>
                    <Ionicons name="swap-horizontal" size={14} color={COLORS.primary} />
                  </View>
                </TouchableOpacity>
              ) : null}
              {onMove ? (
                <>
                  <TouchableOpacity disabled={index === 0} onPress={() => onMove(item, -1)} hitSlop={8}>
                    <View style={[styles.iconActionBtn, index === 0 && styles.iconActionBtnDisabled]}>
                      <Ionicons name="chevron-up" size={13} color={index === 0 ? COLORS.border : COLORS.ink} />
                    </View>
                  </TouchableOpacity>
                  <TouchableOpacity disabled={index === dayItems.length - 1} onPress={() => onMove(item, 1)} hitSlop={8}>
                    <View style={[styles.iconActionBtn, index === dayItems.length - 1 && styles.iconActionBtnDisabled]}>
                      <Ionicons name="chevron-down" size={13} color={index === dayItems.length - 1 ? COLORS.border : COLORS.ink} />
                    </View>
                  </TouchableOpacity>
                </>
              ) : null}
              {onDelete ? (
                <TouchableOpacity onPress={() => onDelete(item)} hitSlop={8}>
                  <View style={styles.deleteBtn}>
                    <Ionicons name="close" size={14} color={COLORS.error} />
                  </View>
                </TouchableOpacity>
              ) : null}
            </View>
          ) : null}
        </View>

        <View style={styles.metaRow}>
          {item.attraction.avg_duration_hours != null ? (
            <Text style={styles.itemDur}>~{item.attraction.avg_duration_hours}h</Text>
          ) : null}
          {fee ? <Text style={styles.itemDur}> - {fee}</Text> : null}
        </View>

        <View style={styles.itemTags}>
          {(item.attraction.tags || []).slice(0, 2).map((tag) => (
            <View key={tag} style={styles.tag}>
              <Text style={styles.tagText}>{formatTag(tag)}</Text>
            </View>
          ))}
        </View>

        {reason ? <Text style={styles.reasonText} numberOfLines={2}>{reason}</Text> : null}
        {fit ? <Text style={styles.groupFitText}>{fit}</Text> : null}
        {leg ? (
          <Text style={styles.legText}>{leg}</Text>
        ) : leg === null ? (
          <Text style={styles.legText}>Route unavailable</Text>
        ) : index < dayItems.length - 1 ? (
          <Text style={styles.legText}>Calculating route...</Text>
        ) : null}
      </View>
    </View>
  );
}

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: COLORS.cream },
  header: {
    backgroundColor: COLORS.cream,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.border,
    paddingHorizontal: 20,
    paddingBottom: 12,
  },
  headerRow: { flexDirection: 'row', alignItems: 'center', gap: 10, marginTop: 8 },
  backBtn: {
    width: 36,
    height: 36,
    borderRadius: RADIUS.full,
    backgroundColor: COLORS.surface,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 10,
  },
  backBtnText: { fontSize: 18, color: COLORS.ink },
  iconBox: {
    width: 34,
    height: 34,
    borderRadius: 9,
    backgroundColor: COLORS.tagBg,
    justifyContent: 'center',
    alignItems: 'center',
  },
  brandText: { fontSize: 18, ...TYPE.serifItalic, color: COLORS.ink },
  tripLabelRow: { marginLeft: 'auto', flexDirection: 'row', alignItems: 'center', gap: 6 },
  tripLabel: { fontSize: 12, color: COLORS.sub, fontFamily: FONTS.sans },
  autoBadge: { backgroundColor: COLORS.tagBg, borderRadius: RADIUS.full, paddingVertical: 3, paddingHorizontal: 10 },
  autoBadgeText: { fontSize: 11, color: COLORS.primary, fontFamily: FONTS.sansSemi },
  tabsRow: { flexDirection: 'row', gap: 7, paddingTop: 14, paddingBottom: 2 },
  tab: { paddingVertical: 7, paddingHorizontal: 16, borderRadius: RADIUS.full, backgroundColor: COLORS.surface },
  tabActive: { backgroundColor: COLORS.primary },
  tabText: { fontSize: 13, color: COLORS.sub, fontFamily: FONTS.sans },
  tabTextActive: { color: COLORS.surface, fontFamily: FONTS.sansSemi },
  scroll: { flex: 1 },
  scrollContent: { paddingHorizontal: 20, paddingTop: 6, paddingBottom: 16 },
  dayHeader: { flexDirection: 'row', alignItems: 'baseline', gap: 10, marginBottom: 16, marginTop: 10 },
  dayTitle: { fontSize: 23, ...TYPE.serifItalic, color: COLORS.ink, flex: 1 },
  routeKm: { fontSize: 11, color: COLORS.primary, fontFamily: FONTS.sansMedium },
  emptyState: { alignItems: 'center', paddingTop: 40 },
  emptyText: { fontSize: 14, color: COLORS.sub, fontFamily: FONTS.sans },
  timelineRow: { flexDirection: 'row', gap: 14, minHeight: 60 },
  timelineLeft: { width: 16, alignItems: 'center', paddingTop: 3 },
  dot: { width: 14, height: 14, borderRadius: 7, borderWidth: 3, borderColor: COLORS.primary, backgroundColor: COLORS.surface },
  line: { flex: 1, width: 2, backgroundColor: COLORS.primary, opacity: 0.3, marginVertical: 4 },
  timelineContent: { flex: 1, paddingBottom: 16 },
  nameRow: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  itemName: { fontSize: 15, color: COLORS.ink, fontFamily: FONTS.sansBold },
  itemActions: { flexDirection: 'row', alignItems: 'center', gap: 5 },
  iconActionBtn: {
    width: 26,
    height: 26,
    borderRadius: 13,
    backgroundColor: COLORS.surface,
    alignItems: 'center',
    justifyContent: 'center',
  },
  iconActionBtnDisabled: { opacity: 0.5 },
  deleteBtn: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: 'rgba(231,111,81,0.1)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  replaceBtn: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: 'rgba(42,157,143,0.1)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  memoryLikeBtn: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: 'rgba(42,157,143,0.1)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  memoryDislikeBtn: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: 'rgba(231,111,81,0.1)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  metaRow: { flexDirection: 'row', marginTop: 2 },
  itemDur: { fontSize: 12, color: COLORS.sub, fontFamily: FONTS.sans },
  itemTags: { flexDirection: 'row', flexWrap: 'wrap', gap: 5, marginTop: 6 },
  tag: { backgroundColor: COLORS.tagBg, borderRadius: RADIUS.full, paddingVertical: 3, paddingHorizontal: 8 },
  tagText: { fontSize: 11, color: COLORS.primary, fontFamily: FONTS.sansMedium },
  reasonText: { fontSize: 11, color: COLORS.ink, fontFamily: FONTS.sans, lineHeight: 16, marginTop: 6 },
  groupFitText: { fontSize: 11, color: COLORS.primary, fontFamily: FONTS.sansSemi, marginTop: 4 },
  legText: { fontSize: 11, color: COLORS.muted, fontFamily: FONTS.sansMedium, marginTop: 6 },
  footer: {
    backgroundColor: COLORS.surface,
    borderTopWidth: 1,
    borderTopColor: COLORS.border,
    paddingHorizontal: 20,
    paddingTop: 12,
  },
  statsBar: { backgroundColor: COLORS.cream, borderRadius: RADIUS.md, paddingVertical: 10, paddingHorizontal: 14, marginBottom: 12 },
  statsText: { fontSize: 12, color: COLORS.ink, fontFamily: FONTS.sansMedium, textAlign: 'center', letterSpacing: 0 },
  footerBtns: { flexDirection: 'row', gap: 12 },
  editBtn: {
    height: 52,
    paddingHorizontal: 20,
    borderRadius: RADIUS.full,
    borderWidth: 1.5,
    borderColor: COLORS.border,
    justifyContent: 'center',
    alignItems: 'center',
  },
  editBtnText: { fontSize: 15, color: COLORS.ink, fontFamily: FONTS.sans },
  regenerateBtn: {
    height: 52,
    paddingHorizontal: 16,
    borderRadius: RADIUS.full,
    borderWidth: 1.5,
    borderColor: COLORS.primary,
    backgroundColor: 'rgba(42,157,143,0.08)',
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'row',
    gap: 6,
  },
  regenerateBtnText: { fontSize: 13, color: COLORS.primary, fontFamily: FONTS.sansSemi },
  saveBtn: {
    flex: 1,
    height: 52,
    borderRadius: RADIUS.full,
    backgroundColor: COLORS.primary,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: COLORS.primary,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.4,
    shadowRadius: 12,
    elevation: 8,
  },
  saveBtnDisabled: { opacity: 0.65 },
  saveBtnText: { fontSize: 18, ...TYPE.serifItalic, color: COLORS.surface },
});
